name: Build the workspace package

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: workspace/package.json

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: workspace/pnpm-lock.yaml

      - name: Build workspace package
        run: |
          cd workspace
          pnpm install --frozen-lockfile
          pnpm run build
