name: Run Integration Tests - Node Dapp

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies in the workspace folder
        run: |
          cd workspace
          npm install

      - name: Install dependencies and run tests in node-dapp folder
        run: |
          cd node-dapp
          npm install
          npm run test
