name: Run the ts-nextjs-app tests

on:
  pull_request:
    branches-ignore:
      - '**'
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install node
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build workspace local package
        run: |
          cd workspace
          npm install
          npm run build

      - name: Run ts-nextjs-app tests
        run: |
          cd examples/ts-nextjs-app
          npm install
          npm run test:ci
