name: Run the js-node-app tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: |
            workspace/pnpm-lock.yaml
            examples/js-node-app/pnpm-lock.yaml

      - name: Build workspace local package
        run: |
          cd workspace
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Run js-node-app tests
        run: |
          cd examples/js-node-app
          pnpm install --frozen-lockfile
          pnpm run test:ci
