name: Run the ts-nextjs-app tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install node
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 8.9.0

      - name: Build workspace local package
        run: |
          cd workspace
          pnpm install
          pnpm build

      - name: Run ts-nextjs-app tests
        run: |
          cd examples/ts-nextjs-app
          pnpm install
          pnpm test:ci
