name: Run the ts-node-app tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install node
      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Build workspace local package
        run: |
          cd workspace
          npm install
          npm run build

      - name: Install ts-node-app dependencies
        run: |
          cd examples/ts-node-app
          npm install
          npx tsc --project tsconfig.testing.json
          npm run test:ci
