name: Run the ts-nextjs-app tests

on:
  pull_request:
    branches-ignore:
      - '**'
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: workspace/package.json

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: |
            workspace/pnpm-lock.yaml
            examples/ts-nextjs-app/pnpm-lock.yaml

      - name: Build workspace local package
        run: |
          cd workspace
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Run ts-nextjs-app tests
        run: |
          cd examples/ts-nextjs-app
          pnpm install --frozen-lockfile
          pnpm run test:ci
